---
- Documentation:
    - Arch Wiki:
        - icon: arch-linux
          href: https://wiki.archlinux.org/
    - Suricata Docs:
        - icon: /icons/suricata.svg
          href: https://docs.suricata.io/
    - Netdata Docs:
        - icon: /icons/netdata.png
          href: https://learn.netdata.cloud/
- Local Lab:
    - Nyx Gitea:
        - icon: /icons/gitea.png
          href: https://git.lan/foreverlx/nyx
    - Nyx Backups:
        - icon: /icons/gitea.png
          href: https://git.lan/foreverlx/backups
