- search:
    provider: custom
    url: https://search.lan/search?q=
    suggestionUrl: https://search.lan/autocompleter?q=
    showSearchSuggestions: true
    target: _blank
- datetime:
    format:
      timeStyle: short
      dateStyle: medium
      hourCycle: h23
